CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

--
-- Common Shared Data Model for awards
--


CREATE TABLE "identity" (
    "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    "created" timestampz NOT NULL DEFAULT current_timestamp,
    "updated" timestampz NOT NULL DEFAULT current_timestamp,

    "type" text,

    "identity_id" text,
    "display_name" text,
    "display_affiliation" text,

    "access_token" text,
    "refresh_token" text,
    "access_scope" text,
    "access_token_expire" int
);


CREATE TABLE "file" (
    "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    "created" timestampz NOT NULL DEFAULT current_timestamp,
    "updated" timestampz NOT NULL DEFAULT current_timestamp,

    "file_name" text,
    "file_display_name" text,
    "file_mime_type" text,
    "file_byte_size" int,

    "storage_type" text,
    "storage_key" text,

    "order" int,
    "confirmed" boolean
);


CREATE TABLE "awardee" (
    "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    "created" timestampz NOT NULL DEFAULT current_timestamp,
    "updated" timestampz NOT NULL DEFAULT current_timestamp,

    "first_name" text,
    "last_name" text,
    "affiliation" text,
    "email" text,

    "identity_id" uuid REFERENCES "identity"
);


-- Award Submission specific tables
--

CREATE TABLE "award-submission" (
    "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    "created" timestampz NOT NULL DEFAULT current_timestamp,
    "updated" timestampz NOT NULL DEFAULT current_timestamp,

    "citation" text,
    "date" timestamp,
    "award_type" text,
    "outcome" text
);


CREATE TABLE "award-submission-files" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY,
    "award_submission_id" uuid REFERENCES "award-submission",
    "file_id" uuid REFERENCES "file",
    "order" as int
);


CREATE TABLE "award-submission-awardees" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY,
    "award_submission_id" uuid REFERENCES "award-submission",
    "awardee_id" uuid REFERENCES "awardee",
    "order" as int
);



--- Awardee Acceptance ---
--

CREATE TABLE "awardee-acceptance" (
    "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    "created" timestampz NOT NULL DEFAULT current_timestamp,
    "updated" timestampz NOT NULL DEFAULT current_timestamp,

    "comments" text,
    "acceptance_outcome" text,
    "publishing_outcome" text,

    "award_submission_id" uuid REFERENCES "award-submission",
    "awardee_id" uuid REFERENCES "awardee"
);